DISCOURSE_SECRET = 'secret'
DISCOURSE_API_USERNAME = 'user'
DISCOURSE_API_KEY = 'key'
DISCOURSE_DOMAIN = 'http://discuss.example.com'
DISCOURSE_PYBOSSA_IP = '1.2.3.4'
DISCOURSE_AUTO_UPDATE_SETTINGS = False
